#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

echo "-----> Installing ghostscript ..."
apt-get -y update
sudo apt-get install ghostscript
echo "-----> ghostscript installed!"
sleep 1 # wait so that docker run has not exited before docker attach
